import requests
import postcode as pc


def name_trunc(input_string: str) -> str:

    count = 0
    output_string = ""

    for letter in input_string:
        output_string += letter
        count += 1
        if count == 3:
            return output_string


def fuel_percentage():
    headers = {
        'Accept': 'application/json'
    }

    url = "https://api.carbonintensity.org.uk/generation"

    r = requests.get(url, params={}, headers=headers)

    status_code = r.status_code

    if status_code == 200:

        data = r.json()

        actual = (data['data']['generationmix'][3])
        fuel_type = actual['fuel']
        percentage = actual['perc']

        output = f": {fuel_type} is generating {percentage}% of electricity."

        return output

    else:
        return "Server error."


def local_gas(postcode):

    outgoing = pc.extract_outer(postcode)

    headers = {
        'Accept': 'application/json'
    }

    url = f"https://api.carbonintensity.org.uk/regional/postcode/{outgoing}"

    r = requests.get(url, params={}, headers=headers)

    status_code = r.status_code

    if status_code == 200:

        data = r.json()

        actual = (data['data'][0]['data'][0]['generationmix'][3])
        fuel_type = actual['fuel']
        percentage = actual['perc']

        output = f"In {outgoing}, {percentage}% of electricity is generated by {fuel_type}."

        return output

    if status_code == 400:

        error_msg = "Postcode not found, defaulting to national data"
        national_data = fuel_percentage()
        return error_msg + national_data

    if status_code == 500:

        return "Server error, service unavailable."
